apiVersion: executor.testkube.io/v1
kind: Executor
metadata:
  name: soapui-executor
  namespace: testkube
spec:
  executor_type: job  
  image: kubeshop/testkube-executor-soapui:latest
  types:
  - soapui/rest
  - soapui/soap
  content_types:
  - string
  - file-uri
  features: 
  - reports
  - extensions
  - plugins
  - arguments
